---
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  options:
    v: true
  log: true
platforms:
  - name: masked-keepalived-focal
    pre_build_image: true
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
